config/routes.rb
Rails.application.routes.draw do

  root "users#login_jira"

  resource :users do
    collection do
      get :login_jira
      post :jira_credentials
      get :show_user_details
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
require "base64"
require 'httparty'

class UsersController < ApplicationController

	def login_jira
    end
	def jira_credentials
		@user = User.find_or_create_by(user_params)
    	enc   = Base64.encode64("#{@user.jira_username}:#{@user.jira_password}")
        header = {"Authorization" => "Basic #{enc}","Content-Type"=> "application/json"} 
        response = HTTParty.get("http://172.16.0.166/rest/api/2/user?username=#{@user.jira_username}", :headers => header )
        @detail = response.parsed_response
	end

	def show_user_details
	end



	private 
	def user_params
		p params
		params.require(:user).permit(:jira_username, :jira_password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JiraAutomation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/jira_credentials.html.erb
<%= @detail.inspect %>

app/views/users/login_jira.html.erb
<%= form_for User.new, as: :user, url: jira_credentials_users_path do |f| %>
 User name <%= f.text_field :jira_username %>
 Password : <%= f.text_field :jira_password %>
 <%= f.submit %>
<% end %>